### ISSUE TITLE
Newer sklearn version changes results completely

### ISSUE THREAD

**Issue by felixholm** [CAMMA-public/ivtmetrics#3]
It appears that with sklearn version 1.1.1 the triplet classes not represented in the test sample will not be represented as nan anymore.
The following warning is shown as well:
`../lib/python3.8/site-packages/sklearn/metrics/_ranking.py:877: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.`
The resulting classwise AP vector from `average_precision_score` does not have nan for unrepresented classes, but `-0.`, which changes the results completely (significantly lower, e.g. 0.87 mAP to 0.24 mAP).

Tested with sklearn versions 1.0.2 and 1.1.1

**Comment by nwoyecid** [comment]
Thank you for the information, we will inspect how the latest update of sklearn lib affects the behaviour of ivtmetrics. For the meantime, we encourage all users to stick with sklearn <= 1.02 for comparable results. Meanwhile, we will be rolling out a custom 'no library' implementation of AP metrics. This will replace the sklearn in our next release.

**Comment by felixholm** [comment]
Great to hear, thank you.
I took some screenshots for illustration, maybe they'll help you as well:
![grafik](https://user-images.githubusercontent.com/104528712/184195174-a76bce83-e9c6-4a7e-8456-a6f2c5e8b61e.png)

![grafik](https://user-images.githubusercontent.com/104528712/184195719-3e3acd9a-e869-463f-a8b3-04d7307a2763.png)

**Comment by nwoyecid** [comment]
Value issue with sklearn version update is now resolved in the ivtmetrics v0.1.1
Thank you
