### ISSUE TITLE
compute_video_AP  'list' object has no attribute 'reshape'

### ISSUE THREAD

**Issue by summerEVEN** [CAMMA-public/ivtmetrics#9]
An error is reported after the compute_video_AP() function is called.
File "/lib/python3.9/site-packages/ivtmetrics/recognition.py", line 184, in compute_video_AP
video_log.append( classwise.reshape([1,-1]) )
AttributeError: 'list' object has no attribute 'reshape'

**Comment by nwoyecid** [comment]
Update ivtmetircs
